### ISSUE TITLE
[Bug] Strange sprite behavior

### ISSUE THREAD

**Issue by time-axis** [falko17/aaoffline#5] opened 2024-12-26 16:46 UTC
I've tried downloading this trial: https://aaonline.fr/forum/viewtopic.php?t=13869

After playing through the first couple minutes, one of the characters, "Scion" seems to be swapping to a different sprite. See here:

![scion bug](https://github.com/user-attachments/assets/1476531a-527c-4e73-876d-57c0e80bd885)

This is not the correct sprite. The correct one is the black woman sprite by CallieG. Which one appears where seems to be arbitrary, or at least I couldn't detect a pattern to it. Maybe something to do with the character's positioning in the scene.

I checked the case on AAO itself, rather than offline, and this does not occur, so I've concluded that it's a bug specific to aaoffline.

One hypothesis I have is that maybe downloading all the assets together into one folder might cause problems when there are assets that have the same file name but different directories. (But I haven't actually looked into the files of the case to check that, as I didn't want to spoil myself on the case). It seems like this is handled properly in other cases, but maybe it's falsely counting different capitalization as having a different file name? Not sure.

Worth pointing out, I am on windows, which treats files with different capitalization but otherwise identical file names as the same. So if it works on different OS than Windows, that would confirm that that's the issue.

**Comment by falko17** [comment] 2024-12-26 23:54
You were absolutely right: This issue was indeed caused by Windows' case-insensitive file system behavior. I fixed it in #6. When that's merged, I'll create another release. Once again, thanks for the bug report, and especially for all the details!

**Closed** 2024-12-27 00:08 UTC
Labels: bug
